config/routes.rb
Trisphere::Application.routes.draw do
  root "index#index"
  
  post "/login" => "index#login"
  get "/logout" => "index#logout"
  
  scope "/character" do
  	get "/" => "character#home"
 	end
  
  scope "/friends" do
  	get "/" => "friends#index", as: "friends"
  	post "/add" => "friends#add", as: "add_friend"
  	get "/remove/:username" => "friends#remove", as: "remove_friend"
  end
  
  scope "/inventory" do
	  get "/" => "inventory#index"
	  get "/bags" => "inventory#bags"
	  get "/equipped" => "inventory#equipped"
	  get "/reset" => "inventory#reset"
	  post "/equip" => "inventory#equip"
	  post "/unequip" => "inventory#unequip"
	  get "/stats" => "inventory#stats"
	end
  
  scope "/forums" do
	  constraints category_id: /\d+/, topic_id: /\d+/, post_id: /\d+/ do
		  get "/" => "forums#index"
		  get "/post/:category_id/(:topic_id)/(:post_id)" => "forums#post"
		  post "/post/:category_id/(:topic_id)/(:post_id)" => "forums#post"
		  post "/make_post/:category_id" => "forums#make_post"
		  get "/:category_id" => "forums#category"
		  get "/:category_id/:topic_id" => "forums#topic"
		  get "/delete/:category_id/:topic_id/:id" => "forums#delete"
		  get "/:alter_type/:category_id/:topic_id" => "forums#alter", constraints: { alter_type: /sticky|unsticky|lock|unlock/ }
		end
	end
	
	scope "/world" do
		get "/" => "world#index"
	end
	
	scope "/explore" do
		get "/" => "explore#index", as: "explore"
		get "/explore" => "explore#explore"
		get "/attack" => "explore#attack"
		get "/skill" => "explore#skill"
	end
	
	scope "/test" do
		get "/" => "test#index"
		get "/colorize" => "test#colorize"
	end
  

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	def index
		@friendships = @user.friendships.includes(:friend).sort_by { |f| f.friend.active_at }.reverse!
		@users = Hash[*@friendships.map { |friend| [friend.friend.id, friend.friend] }.flatten]
	end
	
	def add
		username = params[:username].to_s
		note = params[:note]
		user = User.where(username: username).first
		raise "Unknown user: #{username}" unless user
		@user.befriend(user, note)
		flash[:info] = "#{username} is now your friend"
		redirect_to :friends and return
	rescue => e
		flash[:error] = e.message
		redirect_to :friends and return
	end
	
	def remove
		username = params[:username].to_s
		user = User.where(username: username).first
		@user.unfriend(user)
		flash[:info] = "You have removed #{username} from your friends list"
		redirect_to :friends and return
	end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<div id="friends-header" class="page-header grid">
	<div class="col-3" id="friends-title"><a>Friends List</a></div>
	<div class="col-9 align-right">
		<%= form_tag add_friend_path do %>
			<%= text_field_tag "username", nil, placeholder: "username", size: 12 %>
			<%= text_field_tag "note", nil, placeholder: "note (optional)", size: 24 %>
			<%= button_tag icon("plus") + " Add Friend", type: :submit %>
		<% end %>
	</div>
</div>

<table id="friends-table" class="tri-table">
	<colgroup>
		<col span=1 class="status-column"></col>
		<col span=1 class="name-column"></col>
		<col span=1 class="active-column"></col>
		<col span=1 class="note-column"></col>
		<col span=1 class="actions-column"></col>
	</colgroup>
	<thead>
		<th></th>
		<th>Username</th>
		<th>Last Seen</th>
		<th>Note</th>
		<th>Actions</th>
	</thead>
	<tbody>
		<% @friendships.each do |friendship| %>
			<% friend = friendship.friend %>
			<tr>
				<td class="status"><%= image_tag "stats/spirit.png", width: 20, height: 20, class: friend.online? ? "online" : "offline" %></td>
				<td class="name"><%= name_link(friend.id) %></td>
				<td class="active"><%= friend.online? ? content_tag(:span, "Online", class: "online-tag") : duration_ago(friend.active_at) || "Unknown" %></td>
				<td class="note"><%= friendship.note %></td>
				<td class="actions"><%= link_to "#{icon("remove")} Remove".html_safe, remove_friend_path(username: friend.username), class: "button", confirm: "Remove friend #{friend}?" %></td>
			</tr>
		<% end %>
	</tbody>
</table>